language: node_js

node_js: 8

env:
  - NODE_ENV=ci

install:
  - npm ci

script:
  - npm run build

deploy:
  local_dir: dist
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  keep_history: true
  on:
    branch: master
